### ISSUE TITLE
Refactor TODO list

### ISSUE THREAD

**Issue by toadkicker** [toadkicker/railsstrap#47]
Goals:
- Remove generators - It's easier to maintain helper methods for `javascript_link_tag` and `stylesheet_link_tag` like `<%= stylesheet_link_tag font_awesome_css %>`
- Support more than just rails - Rails is opinionated and the current gem status isn't flexible enough to use another framework if desired. I'd like to open support for more ruby frameworks.
- Provide a CDN helper for railsstrap specific enhancements to bootstrap

Branch: `feature/refactor`
- [x] Support Padrino
- [x] Support Middleman
- [x] Make install generator optional and for additional supporting js/css and i18n support.
- [x] Restructure to better support growing number of helpers with base class(es) and helpers extending them
- [x] Refactor tests for easier grouping across platforms
- [x] Add Dropdown helper
- [x] Add Button Helper
- [x] Add CDN Helper
- [x] Move glyph and fontawesome helpers to single icon helper
- [x] Refactor panel helper to card helper
- [x] Add progress bar helper
- [x] Add collapse helper
- [x] Refactor form error helper so it works with ActionView
- [x] Integrate with form_for and action_view
- [x] Refactor navbar helper
- [x] Add nav helper
- [x] Refactor aside helper
- [x] Refactor datepicker helper
- [ ] Refactor breadcrumbs helper
- [x] Create link_to helper
- [x] Create a CDN helper for railsstrap assets

**Comment by toadkicker** [comment]
On remove generators item, this largely applies to the install generator. There really is quite a pain point in the approach that twitter-bootstrap-rails took to mangling people's css/js files. Instead in 3.3.3 we'll provider helpers for linking assets with standard action view methods.

**Comment by toadkicker** [comment]
Since this is largely done except breadcrumbs, closing this and just making a ticket for breadcrumbs
